DROP TABLE IF EXISTS TRADES;
CREATE TABLE TRADES (
TRADE_ID VARCHAR2(10),
VERSION INT(3),
COUNTER_PARTY_ID VARCHAR2(10),
BOOK_ID VARCHAR2(10),
MATURITY_DATE DATE,
CREATED_DATE DATE,
EXPIRED VARCHAR2(2)
);  